/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'laquah' at '1/18/18 3:20 PM' with Gradle 3.1
 *
 * @author laquah, @date 1/18/18 3:20 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
